---
- name: LNMT
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  remote_user: '{{admin_username}}'

  roles:
    - {role: common, tags: "common"}
    - {role: nginx_for_tomcat, tags: "nginx_for_tomcat "} 
    - {role: tomcat,tags: "tomcat"}
    - {role: mysql,tags: "mysql"}
    - {role: jspmyadmin,tags: "jspmyadmin"}
    - {role: 9panel,tags: "9panel"}
    - {role: other,tags: "other"}

   